environments:
  staging:
    values:
      - env: "staging"
      - rootPath: "../helmfile"
  production:
    values:
      - env: "production"
      - rootPath: "../helmfile"
--- 

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: db-{{ .Environment.Name }}
    chart: bitnami/postgresql
    version: ~12.1.3
    values:
      - values/{{ .Environment.Name }}/db.yaml
  - name: db-pv-{{ .Environment.Name }}
    chart: charts/db
    version: 0.0.1
    values:
      - values/{{ .Environment.Name }}/db.yaml
