apiVersion: apps/v1

kind: Deployment

metadata:
  name: exchange-{{ .Values.env }}
  labels:
    app: exchange-{{ .Values.env }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: exchange-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: exchange-{{ .Values.env }}
      annotations:
        deploy-date: {{ .Values.release_date_time_utc }}
    spec:
      containers:
        - name: telegads-exchange
          image: peteranikitin/telegads-exchange:latest
          env:
            - name: DATABASE_URL
              value: {{ .Values.DATABASE_URL }}
            
            - name: NEXTAUTH_URL
              value: https://{{ .Values.host }}/api/auth
            
            - name: NEXT_PUBLIC_NEXTAUTH_URL
              value: https://{{ .Values.host }}/api/auth
            
            - name: NEXTAUTH_SECRET
              value: {{ .Values.NEXTAUTH_SECRET }}
            
            - name: API_AUTH_SECRET
              value: {{ .Values.API_AUTH_SECRET }}
            
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.GOOGLE_AUTH_ID }}
            
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.GOOGLE_AUTH_SECRET }}
            
            - name: TG_CONNECTOR_URL
              value: https://tg-connector.nikitin-petr.ru

            - name: TG_BOT_API_URL
              value: {{ .Values.TG_BOT_API_URL }}

            - name: TG_BOT_AUTH
              value: {{ .Values.TG_BOT_AUTH }}

          ports:
            - containerPort: 3000
