version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    stdin_open: true
    container_name: app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL
      - NEXTAUTH_URL
      - NEXT_PUBLIC_NEXTAUTH_URL
      - NEXTAUTH_SECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s