version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=exchange
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data