environments:
  staging:
    values:
      - env: "staging"
      - rootPath: "../helmfile"
  production:
    values:
      - env: "production"
      - rootPath: "../helmfile"
---
bases:
  - releases/test.yaml
