environments:
  staging:
    values:
      - env: "staging"
      - rootPath: "../helmfile"
  production:
    values:
      - env: "production"
      - rootPath: "../helmfile"
---
releases:
  - name: exchange-{{ .Environment.Name }}
    chart: charts/exchange
    version: 0.0.1
    values:
      - values/{{ .Environment.Name }}/exchange.yaml
