version: '3.8'

services:
  db:
    image: peteranikitin/telegads-exchange-db-stage:latest
    ports:
      - '5433:5432'
    networks:
      - network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    image: peteranikitin/telegads-exchange-app-stage:latest
    stdin_open: true
    networks:
      - network
    ports:
      - 3001:3000
    depends_on:
      - db
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001']
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  network:
    driver: bridge
