
# START DEPS IMAGE

FROM node:16-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./


RUN npm i

# END DEPS IMAGE

# START BUILD IMAGE

FROM node:16-alpine AS build
WORKDIR /app
ARG SENTRY_AUTH_TOKEN_ARG

COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN_ARG
ENV DATABASE_URL=$DATABASE_URL
RUN apk update \
  && apk add openssl1.1-compat
RUN npm run prisma-generate

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:bg-task"]
