version: "3.8"

services:
  db:
    image: peteranikitin/telegads-exchange-db-stage:latest
    ports:
      - "5433:5432"
  app:
    image: peteranikitin/telegads-exchange-app-stage:latest
    networks:
      - network
      - tg-connector-stage_tg_connector_network
    ports:
      - 3001:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  network:
    driver: bridge
  tg-connector-stage_tg_connector_network:
    external: true