version: "3.8"

services:
  db:
    image: peteranikitin/telegads-exchange-db-prod:latest
    ports:
      - "5433:5432"
  app:
    image: peteranikitin/telegads-exchange-app-prod:latest
    networks:
      - network
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  network:
    driver: bridge