apiVersion: v1
kind: PersistentVolume 
metadata:
  name: db-{{ .Values.env }}
  labels:
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.capacity.storage }} 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /exchange/{{ .Values.env }}/data/volume
