apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: db-{{ .Values.env }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.capacity.storage }} 
