apiVersion: v1
kind: Service
metadata:
  name: db-node-port-{{ .Values.env }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: db-{{ .Values.env }}
    app.kubernetes.io/name: postgresql
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
      nodePort: {{ .Values.nodePort }}
