export const HTTP_STATUS = {
  NOT_AUTHORIZED: 401,
  OK: 200,
  INTERNAL_ERROR: 503,
  INVALID_CLIENT_REQUEST: 403,
  METHOD_NOT_ALLOWED: 405
};

export const DEFAULT_PAGE_SIZE = 50;
export const DEFAULT_PAGE_SIZE_FOR_UPDATE = 1