name: deploy-to-production

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy production
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /telegads-stage/docker-compose.yml -f /telegads-stage/docker-compose.prod.yml pull && docker compose -f /telegads-stage/docker-compose.yml -f /telegads-stage/docker-compose.prod.yml up --force-recreate --build -d
