name: Deploy - production - docker compose

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy production
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /telegads-prod/docker-compose.prod.yml pull && docker compose -f /telegads-prod/docker-compose.prod.yml up --force-recreate --build -d
