name: ci

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange:latest
          file: ./deploy/Dockerfile

      - name: Build and push staging image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange-app-stage:latest
          file: ./deploy/Dockerfile-app-deploy
          build-args: |
            DATABASE_URL_ARG=postgresql://telegads-staging:${{secrets.DB_PASS_STAGE}}@db:5432/exchange?schema=public
            NEXTAUTH_URL_ARG=http://staging.telegads.uz/api/auth
            NEXT_PUBLIC_NEXTAUTH_URL_ARG=123
            NEXTAUTH_SECRET_ARG=${{secrets.NEXTAUTH_SECRET_ARG}}

      - name: Build and push production image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange-app-prod:latest
          file: ./deploy/Dockerfile-app-deploy
          build-args: |
            DATABASE_URL_ARG=postgresql://telegads-prod:${{secrets.DB_PASS_PROD}}@db:5432/exchange?schema=public
            NEXTAUTH_URL_ARG=http://telegads.uz/api/auth
            NEXT_PUBLIC_NEXTAUTH_URL_ARG=123
            NEXTAUTH_SECRET_ARG=${{secrets.NEXTAUTH_SECRET_ARG}}
