name: deploy-to-staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange:latest
          file: ./deploy/Dockerfile
          build-args: |
            SENTRY_AUTH_TOKEN_ARG=${{secrets.SENTRY_AUTH_TOKEN}}

      - name: Build and push staging image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange-app-stage:latest
          file: ./deploy/Dockerfile-app-deploy
          build-args: |
            DATABASE_URL_ARG=postgresql://telegads-staging:${{secrets.DB_PASS_STAGE}}@db:5432/exchange?schema=public
            NEXTAUTH_URL_ARG=https://staging.telegads.uz/api/auth
            NEXT_PUBLIC_NEXTAUTH_URL_ARG=123
            NEXTAUTH_SECRET_ARG=${{secrets.NEXTAUTH_SECRET_ARG}}
            API_AUTH_SECRET_ARG=${{secrets.API_AUTH_SECRET_STAGE}}
            GOOGLE_AUTH_ID_ARG=${{secrets.GOOGLE_AUTH_ID_STAGE}}
            GOOGLE_AUTH_SECRET_ARG=${{secrets.GOOGLE_AUTH_SECRET_STAGE}}
            TG_CONNECTOR_URL_ARG=localhost:3003

      - name: Build and push production image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-exchange-app-prod:latest
          file: ./deploy/Dockerfile-app-deploy
          build-args: |
            DATABASE_URL_ARG=postgresql://telegads-prod:${{secrets.DB_PASS_PROD}}@db:5432/exchange?schema=public
            NEXTAUTH_URL_ARG=https://telegads.uz/api/auth
            NEXT_PUBLIC_NEXTAUTH_URL_ARG=123
            API_AUTH_SECRET_ARG=${{secrets.API_AUTH_SECRET_PROD}}
            SENTRY_AUTH_TOKEN_ARG=${{secrets.SENTRY_AUTH_TOKEN}}
            NEXTAUTH_SECRET_ARG=${{secrets.NEXTAUTH_SECRET_ARG}}
            GOOGLE_AUTH_ID_ARG=${{secrets.GOOGLE_AUTH_ID_PROD}}
            TG_CONNECTOR_URL_ARG=localhost:3004
            GOOGLE_AUTH_SECRET_ARG=${{secrets.GOOGLE_AUTH_SECRET_PROD}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy staging
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /telegads-stage/docker-compose.yml -f /telegads-stage/docker-compose.stage.yml pull && docker compose -f /telegads-stage/docker-compose.yml -f /telegads-stage/docker-compose.stage.yml up --force-recreate --build -d
